//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE_PROJECT_PO.Models
{
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public int ID { get; set; }
        public string CityName { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
    }
}
